export type FontCategoryGroup =
  | "Script"
  | "Cartoon"
  | "Pixel"
  | "Display"
  | "Sans Serif"
  | "Serif"
  | "Signature";

export type FontProduct = {
  rank: number;
  slug: string;
  name: string;
  /** Full descriptive category, e.g. "Script / Handwritten" */
  category: string;
  /** Broad bucket used for catalog filtering */
  categoryGroup: FontCategoryGroup;
  /** Primary SEO keyword this font's landing page targets */
  seoKeyword: string;
  price: number;
  webPrice: number;
  previewFamily: string;
  /** Approximate DaFont free-version downloads — proof of search demand */
  dafontDownloads?: string;
  source: string;
  notes: string;
  badge?: "Bestseller" | "New";
};

// Real 20-font lineup sourced from ibracreative.com (paid catalog) and
// cross-referenced against DaFont download counts for proven search demand.
// Fonts with `dafontDownloads` set have a free version already driving
// traffic on DaFont — the SEO page positions this as the commercial/paid
// upsell for client and business use.
export const fonts: FontProduct[] = [
  {
    rank: 1,
    slug: "alexandra-signature-font",
    name: "Alexandra Signature",
    category: "Script / Handwritten",
    categoryGroup: "Script",
    seoKeyword: "alexandra signature font free download",
    price: 14,
    webPrice: 27,
    previewFamily: "'Brush Script MT', cursive",
    dafontDownloads: "65,900+",
    source: "DaFont #1 by downloads + ibracreative.com paid version",
    notes: "Free version drives massive discovery — the paid commercial license is the core upsell.",
    badge: "Bestseller",
  },
  {
    rank: 2,
    slug: "comicoon-cartoon-font",
    name: "Comicoon",
    category: "Fancy / Cartoon",
    categoryGroup: "Cartoon",
    seoKeyword: "cartoon font free download comic style",
    price: 12,
    webPrice: 23,
    previewFamily: "'Comic Sans MS', cursive",
    dafontDownloads: "28,600+",
    source: "DaFont #2 by downloads",
    notes: "Comic/cartoon fonts convert heavily on Canva, kids content, and YouTube thumbnails.",
  },
  {
    rank: 3,
    slug: "mominacute-handwritten-font",
    name: "Mominacute",
    category: "Script / Handwritten",
    categoryGroup: "Script",
    seoKeyword: "cute handwritten font free download",
    price: 12,
    webPrice: 23,
    previewFamily: "cursive",
    dafontDownloads: "17,100+",
    source: "DaFont #3 by downloads",
    notes: "Strong in the aesthetic design community; popular with Instagram content creators.",
  },
  {
    rank: 4,
    slug: "pixelate-pixel-font",
    name: "Pixelate",
    category: "Bitmap / Pixel",
    categoryGroup: "Pixel",
    seoKeyword: "pixel font bitmap retro game font",
    price: 9,
    webPrice: 17,
    previewFamily: "'Courier New', monospace",
    dafontDownloads: "18,100+",
    source: "DaFont #4 by downloads",
    notes: "Pixel font buyers are game devs and streamers — converts well priced under $10.",
  },
  {
    rank: 5,
    slug: "rachelasti-display-font",
    name: "Rachelasti",
    category: "Basic / Various",
    categoryGroup: "Display",
    seoKeyword: "modern display font free commercial use",
    price: 9,
    webPrice: 17,
    previewFamily: "Arial, sans-serif",
    dafontDownloads: "7,400+",
    source: "DaFont",
    notes: "Steady daily downloads; upsell on the commercial license.",
  },
  {
    rank: 6,
    slug: "boxiest-bubble-font",
    name: "Boxiest",
    category: "Fancy / Cartoon",
    categoryGroup: "Cartoon",
    seoKeyword: "bubble font rounded cartoon letters",
    price: 12,
    webPrice: 23,
    previewFamily: "'Comic Sans MS', cursive",
    dafontDownloads: "7,300+",
    source: "DaFont",
    notes: "Bubble fonts have strong commercial demand from teachers, kids brands, sticker makers.",
  },
  {
    rank: 7,
    slug: "qigome-monoline-font",
    name: "Qigome Monoline",
    category: "Fancy / Cartoon / Monoline",
    categoryGroup: "Cartoon",
    seoKeyword: "monoline font thin line cartoon font",
    price: 12,
    webPrice: 23,
    previewFamily: "cursive",
    dafontDownloads: "6,700+",
    source: "DaFont",
    notes: "Monoline aesthetic is trending for logos and branding; pairs well with a premium upsell.",
  },
  {
    rank: 8,
    slug: "bublah-cartoon-font",
    name: "Bublah",
    category: "Fancy / Cartoon",
    categoryGroup: "Cartoon",
    seoKeyword: "playful cartoon display font modern",
    price: 12,
    webPrice: 23,
    previewFamily: "'Comic Sans MS', cursive",
    dafontDownloads: "6,100+",
    source: "DaFont",
    notes: "Playful, modern cartoon style — strong for children's brand designers.",
  },
  {
    rank: 9,
    slug: "gailes-sans-serif-font",
    name: "Gailes",
    category: "Basic / Sans Serif",
    categoryGroup: "Sans Serif",
    seoKeyword: "clean modern sans serif font free",
    price: 14,
    webPrice: 27,
    previewFamily: "'Helvetica Neue', sans-serif",
    dafontDownloads: "9,400+",
    source: "DaFont",
    notes: "'Modern sans serif' has high global search volume; strong for branding designers.",
  },
  {
    rank: 10,
    slug: "kolaron-condensed-font",
    name: "Kolaron",
    category: "Display / Condensed Sans Serif",
    categoryGroup: "Display",
    seoKeyword: "modern condensed sans serif font",
    price: 14,
    webPrice: 27,
    previewFamily: "'Arial Narrow', sans-serif",
    source: "ibracreative.com bestseller + MyFonts",
    notes: "Most-described font on the source site; multilingual support gives a global SEO edge.",
    badge: "Bestseller",
  },
  {
    rank: 11,
    slug: "galberta-futuristic-font",
    name: "Galberta",
    category: "Display / Futuristic Sans Serif",
    categoryGroup: "Display",
    seoKeyword: "futuristic font sci-fi modern sans serif",
    price: 14,
    webPrice: 27,
    previewFamily: "'Arial Black', sans-serif",
    source: "ibracreative.com + MyFonts",
    notes: "Competes well in the 'sci-fi font' and 'tech font' keyword space.",
  },
  {
    rank: 12,
    slug: "rishiona-serif-font",
    name: "Rishiona",
    category: "Serif / Modern Elegant",
    categoryGroup: "Serif",
    seoKeyword: "elegant serif font modern branding",
    price: 14,
    webPrice: 27,
    previewFamily: "Georgia, serif",
    source: "ibracreative.com + Dafont101 mention",
    notes: "'Elegant serif font' is a top buyer keyword among luxury/fashion designers.",
  },
  {
    rank: 13,
    slug: "damonte-adventure-font",
    name: "Damonte",
    category: "Display / Adventure",
    categoryGroup: "Display",
    seoKeyword: "adventure font outdoor rustic display",
    price: 17,
    webPrice: 32,
    previewFamily: "Impact, sans-serif",
    source: "ibracreative.com + AbstractFonts mention ($17)",
    notes: "Outdoor/travel/camping is an underserved niche with passionate Etsy/merch buyers.",
  },
  {
    rank: 14,
    slug: "strateen-techno-font",
    name: "Strateen",
    category: "Display / Futuristic Techno",
    categoryGroup: "Display",
    seoKeyword: "futuristic techno display font sleek",
    price: 14,
    webPrice: 27,
    previewFamily: "'Arial Black', sans-serif",
    source: "Dafont101 (ibracreative credited)",
    notes: "Esports and gaming channels are buyers with real commercial-use intent.",
  },
  {
    rank: 15,
    slug: "lewis-hamilton-signature-font",
    name: "Lewis Hamilton",
    category: "Signature / Script",
    categoryGroup: "Signature",
    seoKeyword: "signature font elegant sports style",
    price: 14,
    webPrice: 27,
    previewFamily: "'Brush Script MT', cursive",
    source: "ibracreative.com + MyFonts",
    notes: "Unique name-recognition positioning; good fit for F1/sports branding and PR hooks.",
  },
  {
    rank: 16,
    slug: "garbentas-minimal-sans-font",
    name: "Garbentas",
    category: "Sans Serif / Modern Minimal",
    categoryGroup: "Sans Serif",
    seoKeyword: "minimalist sans serif font branding logo",
    price: 14,
    webPrice: 27,
    previewFamily: "'Helvetica Neue', sans-serif",
    source: "ibracreative.com Font Fusion blog post",
    notes: "Minimalist sans is the single biggest font-buyer demographic (brand identity designers).",
  },
  {
    rank: 17,
    slug: "befrung-bold-condensed-font",
    name: "Befrung",
    category: "Display / Black Condensed",
    categoryGroup: "Display",
    seoKeyword: "black condensed bold display font headline",
    price: 14,
    webPrice: 27,
    previewFamily: "'Arial Black', sans-serif",
    source: "ibracreative.com Font Fusion blog post",
    notes: "Bold condensed is among the top-selling font styles for poster/editorial designers.",
  },
  {
    rank: 18,
    slug: "parandea-vintage-serif-font",
    name: "Parandea",
    category: "Serif / Vintage",
    categoryGroup: "Serif",
    seoKeyword: "vintage serif font retro classic typeface",
    price: 14,
    webPrice: 27,
    previewFamily: "'Times New Roman', serif",
    source: "ibracreative.com Font Fusion blog post",
    notes: "Vintage aesthetic is perennially popular on Etsy/Canva; wedding stationery buyers convert well.",
  },
  {
    rank: 19,
    slug: "debraht-elegant-sans-font",
    name: "Debraht",
    category: "Sans Serif / Modern Elegant",
    categoryGroup: "Sans Serif",
    seoKeyword: "elegant modern sans serif luxury branding font",
    price: 17,
    webPrice: 32,
    previewFamily: "'Helvetica Neue', sans-serif",
    source: "ibracreative.com Font Fusion blog post",
    notes: "Strong fit for fashion, beauty, and hospitality brand design — buyers pay premium.",
  },
  {
    rank: 20,
    slug: "dunyah-script-font",
    name: "Dunyah",
    category: "Script / Elegant",
    categoryGroup: "Script",
    seoKeyword: "elegant script font wedding invitation",
    price: 14,
    webPrice: 27,
    previewFamily: "'Brush Script MT', cursive",
    source: "ibracreative.com + MyFonts",
    notes: "'Wedding invitation font' is among the highest-converting font keywords — high-LTV buyers.",
  },
];

export const categoryGroups: FontCategoryGroup[] = [
  "Script",
  "Cartoon",
  "Pixel",
  "Display",
  "Sans Serif",
  "Serif",
  "Signature",
];

export function getFontBySlug(slug: string): FontProduct | undefined {
  return fonts.find((f) => f.slug === slug);
}
